Refactor firstboot.d/01ipconfig to support setting wifi (scripts being called don't all exist yet).

diff --git a/firstboot.d/01ipconfig b/firstboot.d/01ipconfig
--- a/firstboot.d/01ipconfig
+++ b/firstboot.d/01ipconfig
@@ -3,37 +3,62 @@
 
 . /etc/default/inithooks
 
+fatal() { echo "FATAL: $@" >&2; exit 1; }
+check_state() {
+    iface_l=$(ip a | grep " $1: ")
+    echo "$iface_l" | sed -En "s|^.*state ([A-Z]+ ).*|\1|p"
+}
+
 [ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
-[ -z "$IP_CONFIG" ] && exit 0
-[ "$IP_CONFIG" != "manual" ] && [ "$IP_CONFIG" != "static" ] && [ "$IP_CONFIG" != "dhcp" ] && exit 1
-[ ! -e /etc/network/interfaces ] && exit 1
-
-# if IP_CONFIG is not changed skip this script and avoid a interface reconfiguration
-grep "iface eth0 inet $IP_CONFIG" /etc/network/interfaces >/dev/null && exit 0
-
-ifdown --exclude=lo -a
-
-# since debian 8 (systemd) ifdown does no longer take the interface down
-# if we change between manual, static or dhcp this does not work anymore
-# as ifup won't do anything
-ip link set eth0 down
-
-echo "# interfaces(5) file used by ifup(8) and ifdown(8)" >/etc/network/interfaces
-echo >>/etc/network/interfaces
-echo "auto lo" >>/etc/network/interfaces
-echo "iface lo inet loopback" >>/etc/network/interfaces
-echo >>/etc/network/interfaces
-echo "auto eth0" >>/etc/network/interfaces
-echo "iface eth0 inet $IP_CONFIG" >>/etc/network/interfaces
-echo " hostname $(head -1 /etc/hostname)" >>/etc/network/interfaces
-
-if [ "$IP_CONFIG" = "static" ]; then
- echo " address $IP_ADDRESS" >>/etc/network/interfaces
- echo " netmask $IP_NETMASK" >>/etc/network/interfaces
- echo " gateway $IP_GW" >>/etc/network/interfaces
- echo " dns-nameservers $IP_DNS1 $IP_DNS2" >>/etc/network/interfaces
+INTERACTIVE_WIFI="${INTERACTIVE_WIFI,,}"
+if [[ "$INTERACTIVE_WIFI" == "true"  ]]; then
+    if [[ "$(check_state wlan0)" =~ [A-Z]+  ]]; then
+        INTERFACE=wlan0
+        $INITHOOKS_PATH/bin/wpa_pass.py
+    fi
+elif [[ -n "$IP_CONFIG" ]]; then
+    if [[ "$INTERFACE" == 'wlan0' ]]; then
+        if [[ -z "$WPA_SSID" ]] || [[ -z "$WPA_PASS" ]];
+            fatal "wlan0 requires SSID & password."
+        fi
+        $INITHOOKS_PATH/bin/wpa_pass.py --ssid="$WPA_SSID" --pass="$WPA_PASS"
+    elif [[ "$(check_state eth0)" =~ [A-Z]+ ]]; then
+        INTERFACE=eth0
+    else
+        fatal "IP_CONFIG set but no interface found."
+    fi
+else
+    exit 0
 fi
+[ ! -e /etc/network/interfaces ] && fatal "Interfaces file not found."
 
+case $INTERFACE in
+    eth0)
+        # if IP_CONFIG unchanged skip this script & avoid iface reconfig
+        grep -q "iface eth0 inet $IP_CONFIG" /etc/network/interfaces \
+            && exit 0;
+    wlan0)
+        continue;;
+    *)
+        fatal "Only eth0 or wlan0 can be pre-configured (not $interface)"
+esac
+
+case $IPCONFIG in
+    manual|dhcp)
+        confconsole-ip-conf $INTERFACE --set="$IPCONFIG"
+    static)
+        if [[ -z "$IP_ADDRESS" ]] || [[ -z "$IP_NETMASK" ]] \\
+                || [[ -z "$IP_GW" ]] || [[ -z "$IP_DNS1"]]; then
+            fatal "static ip needs addr, netmask, gateway & dns."
+        fi;
+        confconsole-ip-conf $INTERFACE \
+            --ip="$IP_ADDRESS" --netm="$IP_NETMASK" \
+            --gatew="$IP_GW" --dns="$IP_DNS1" --dns="$IP_DNS2";;
+    *)
+        fatal "Unrecognised IPCONFIG ($IPCONFIG)";;
+esac
+
+ip link set $interface down
 ifup --exclude=lo -a
 
 exit $?
